// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlajnmqfgwxnysgsajrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsYWpubXFmZ3d4bnlzZ3NhanJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDg5OTQsImV4cCI6MjA3MjcyNDk5NH0.c3nEht3SOIzmyyBCVt9XYpF6G6s7jZyd6090b12LElQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});